package com.billing_client.billing_client.model;


import com.billing_client.billing_client.model.enums.InvoiceType;
import com.billing_client.billing_client.model.enums.InvoiceStatus;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "invoices")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Invoice {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique ID generated by this system to correlate with AFIP.
     * Sent in the SOAP request and echoed back in the SOAP response.
     */
    @Column(name = "external_invoice_id", nullable = false, unique = true)
    private String externalInvoiceId;

    // ─────────────────────────────────────────────
    //  INVOICE CLASSIFICATION
    // ─────────────────────────────────────────────

    @Enumerated(EnumType.STRING)
    @Column(name = "invoice_type", nullable = false)
    private InvoiceType invoiceType;

    @Column(name = "issue_date", nullable = false)
    private LocalDate issueDate;

    @Column(name = "point_of_sale")
    private Integer pointOfSale;

    // ─────────────────────────────────────────────
    //  ISSUER (the company billing)
    // ─────────────────────────────────────────────

    @Column(name = "issuer_cuit", nullable = false)
    private String issuerCuit;

    @Column(name = "issuer_business_name", nullable = false)
    private String issuerBusinessName;

    @Column(name = "issuer_address")
    private String issuerAddress;

    // ─────────────────────────────────────────────
    //  RECEIVER (the customer being billed)
    // ─────────────────────────────────────────────

    @Column(name = "receiver_cuit", nullable = false)
    private String receiverCuit;

    @Column(name = "receiver_business_name", nullable = false)
    private String receiverBusinessName;

    @Column(name = "receiver_address")
    private String receiverAddress;

    // ─────────────────────────────────────────────
    //  AMOUNTS
    // ─────────────────────────────────────────────

    @Column(name = "net_amount", nullable = false, precision = 15, scale = 2)
    private BigDecimal netAmount;

    @Column(name = "vat_amount", nullable = false, precision = 15, scale = 2)
    private BigDecimal vatAmount;

    @Column(name = "total_amount", nullable = false, precision = 15, scale = 2)
    private BigDecimal totalAmount;

    // ─────────────────────────────────────────────
    //  AFIP RESPONSE DATA
    // ─────────────────────────────────────────────

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private InvoiceStatus status;

    /** CAE code returned by AFIP — null if rejected */
    @Column(name = "cae")
    private String cae;

    /** CAE expiration date — null if rejected */
    @Column(name = "cae_expiration_date")
    private LocalDate caeExpirationDate;

    /** Sequential number assigned by AFIP — null if rejected */
    @Column(name = "afip_invoice_number")
    private Long afipInvoiceNumber;

    /** Human-readable message from AFIP (approval note or rejection reason) */
    @Column(name = "afip_message", columnDefinition = "TEXT")
    private String afipMessage;

    // ─────────────────────────────────────────────
    //  AUDIT FIELDS
    // ─────────────────────────────────────────────

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.status = InvoiceStatus.PENDING;
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    // ─────────────────────────────────────────────
    //  RELATIONSHIP
    // ─────────────────────────────────────────────

    /**
     * One invoice has many line items.
     *
     * cascade = ALL     → when we save/delete an invoice, items follow
     * orphanRemoval     → if we remove an item from the list, it gets deleted from DB
     * fetch = LAZY      → items are not loaded from DB until we actually access them
     */
    @OneToMany(mappedBy = "invoice", cascade = CascadeType.ALL,
            orphanRemoval = true, fetch = FetchType.LAZY)
    @Builder.Default
    private List<InvoiceItem> items = new ArrayList<>();
}