spring.application.name=billing-client
server.port=8080

# ===== DATABASE =====
spring.datasource.url=jdbc:postgresql://localhost:5432/billing_db?TimeZone=UTC
spring.datasource.username=billing_user
spring.datasource.password=billing_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ===== AFIP SOAP =====
afip.soap.url=http://localhost:8081/ws/invoice
afip.soap.wsdl=http://localhost:8081/ws/invoice.wsdl

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs


#Security JWT
jwt.secret=3f8a1c2e4b7d9f0a2c5e8b1d4f7a0c3e6b9d2f5a8c1e4b7d0f3a6c9e2b5d8f1
jwt.expiration=86400000