package com.billing_client.billing_client.soap;

import com.billing_client.billing_client.dto.request.InvoiceItemRequestDTO;
import com.billing_client.billing_client.dto.request.InvoiceRequestDTO;
import com.billing_client.billing_client.exception.SoapCommunicationException;
import com.billing_client.billing_client.model.enums.InvoiceType;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import org.springframework.ws.client.core.WebServiceTemplate;
import org.springframework.ws.soap.client.core.SoapActionCallback;
import server.soap.afip.invoice.*;


import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;

@Slf4j
@Component
@RequiredArgsConstructor
public class AfipSoapClient {

    private final WebServiceTemplate webServiceTemplate;

    @Value("${afip.soap.url}")
    private String afipSoapUrl;

    /**
     * Sends an invoice authorization request to the AFIP SOAP server
     * and returns the response.
     *
     * Steps:
     *   1. Build the AuthorizeInvoiceRequest XML object from our DTO
     *   2. Send it via WebServiceTemplate (handles the SOAP envelope automatically)
     *   3. Cast and return the response
     *
     * @param externalInvoiceId unique ID generated by our system for correlation
     * @param request           the invoice data from the REST request
     * @return                  the AFIP authorization response with CAE or errors
     */
    public AuthorizeInvoiceResponse authorize(String externalInvoiceId, InvoiceRequestDTO request) {
        log.info("Sending SOAP request to AFIP — externalInvoiceId: {}", externalInvoiceId);

        try {
            AuthorizeInvoiceRequest soapRequest = buildSoapRequest(externalInvoiceId, request);

            // WebServiceTemplate sends the request and returns the response
            // It wraps the object in a SOAP Envelope automatically
            AuthorizeInvoiceResponse response = (AuthorizeInvoiceResponse)
                    webServiceTemplate.marshalSendAndReceive(
                            afipSoapUrl,
                            soapRequest,
                            new SoapActionCallback("")
                    );

            log.info("SOAP response received — externalInvoiceId: {} | status: {}",
                    externalInvoiceId, response.getStatus());

            return response;

        } catch (Exception e) {
            log.error("SOAP communication error — externalInvoiceId: {} | error: {}",
                    externalInvoiceId, e.getMessage());
            throw new SoapCommunicationException(
                    "Failed to communicate with AFIP SOAP server: " + e.getMessage(), e
            );
        }
    }

    // ─────────────────────────────────────────────
    //  REQUEST BUILDER
    // ─────────────────────────────────────────────

    /**
     * Converts our InvoiceRequestDTO into the JAXB-generated
     * AuthorizeInvoiceRequest that Spring-WS can serialize to XML.
     */
    private AuthorizeInvoiceRequest buildSoapRequest(String externalInvoiceId,
                                                     InvoiceRequestDTO request) {
        AuthorizeInvoiceRequest soapRequest = new AuthorizeInvoiceRequest();

        soapRequest.setExternalInvoiceId(externalInvoiceId);
        soapRequest.setInvoiceType(
                server.soap.afip.invoice.InvoiceType.valueOf(request.getInvoiceType().name())
        );
        soapRequest.setIssueDate(toXmlDate(request.getIssueDate()));

        if (request.getPointOfSale() != null) {
            soapRequest.setPointOfSale(java.math.BigInteger.valueOf(request.getPointOfSale()));
        }

        // Issuer
        TaxpayerInfo issuer = new TaxpayerInfo();
        issuer.setCuit(request.getIssuerCuit());
        issuer.setBusinessName(request.getIssuerBusinessName());
        issuer.setAddress(request.getIssuerAddress());
        soapRequest.setIssuer(issuer);

        // Receiver
        TaxpayerInfo receiver = new TaxpayerInfo();
        receiver.setCuit(request.getReceiverCuit());
        receiver.setBusinessName(request.getReceiverBusinessName());
        receiver.setAddress(request.getReceiverAddress());
        soapRequest.setReceiver(receiver);

        // Items
        AuthorizeInvoiceRequest.Items soapItems = new AuthorizeInvoiceRequest.Items();
        for (InvoiceItemRequestDTO itemDTO : request.getItems()) {
            InvoiceItem soapItem = new InvoiceItem();
            soapItem.setDescription(itemDTO.getDescription());
            soapItem.setQuantity(itemDTO.getQuantity());
            soapItem.setUnitPrice(itemDTO.getUnitPrice());
            soapItem.setVatRate(VatRate.valueOf(itemDTO.getVatRate().name()));
            soapItem.setSubtotal(calculateSubtotal(itemDTO));
            soapItems.getItem().add(soapItem);
        }
        soapRequest.setItems(soapItems);

        // Amounts
        soapRequest.setNetAmount(request.getNetAmount());
        soapRequest.setVatAmount(request.getVatAmount());
        soapRequest.setTotalAmount(request.getTotalAmount());

        return soapRequest;
    }

    // ─────────────────────────────────────────────
    //  HELPER METHODS
    // ─────────────────────────────────────────────

    /**
     * Calculates item subtotal: quantity * unitPrice
     * Rounded to 2 decimal places.
     */
    private BigDecimal calculateSubtotal(InvoiceItemRequestDTO item) {
        return item.getQuantity()
                .multiply(item.getUnitPrice())
                .setScale(2, RoundingMode.HALF_UP);
    }

    /**
     * Converts LocalDate to XMLGregorianCalendar (required by JAXB xs:date)
     */
    private XMLGregorianCalendar toXmlDate(LocalDate date) {
        try {
            return DatatypeFactory.newInstance()
                    .newXMLGregorianCalendar(date.toString());
        } catch (Exception e) {
            throw new RuntimeException("Error converting date: " + date, e);
        }
    }
}